import type { RockThemeIdea } from "@/types/rock";

export const ROCK_DEFAULT_IDEAS: RockThemeIdea[] = [
  { icon: "shield", title: "Napoleon's Last Stand", desc: "The emperor at Waterloo — his final gamble as rain falls on a crumbling empire", color: "#8B0000", iconColor: "#FFD700", categorySlug: "conquerors-kings", characterName: "Napoleon Bonaparte", storyAngle: "The fall of an empire at Waterloo" },
  { icon: "shield", title: "The Wrath of Genghis Khan", desc: "From orphaned boy on the steppe to the most feared conqueror in history", color: "#8B0000", iconColor: "#FFD700", categorySlug: "conquerors-kings", characterName: "Genghis Khan", storyAngle: "Uniting the Mongol tribes through sheer will" },
  { icon: "local_fire_department", title: "Spartacus: Break Every Chain", desc: "A gladiator who turned the arena's blood into a revolution", color: "#FF4500", iconColor: "#FFF", categorySlug: "rebels-outlaws", characterName: "Spartacus", storyAngle: "The largest slave revolt in Roman history" },
  { icon: "local_fire_department", title: "Blackbeard's Last Voyage", desc: "The pirate king's final battle — five bullets and twenty sword wounds", color: "#FF4500", iconColor: "#FFF", categorySlug: "rebels-outlaws", characterName: "Blackbeard", storyAngle: "The last stand at Ocracoke Inlet" },
  { icon: "lightbulb", title: "Tesla vs. Edison: War of Currents", desc: "Genius versus business — the man who lit the world vs the man who took the credit", color: "#FFD700", iconColor: "#1A1A1A", categorySlug: "visionaries-inventors", characterName: "Nikola Tesla", storyAngle: "AC vs DC, the rivalry that shaped modern electricity" },
  { icon: "lightbulb", title: "Da Vinci's Secret Machine", desc: "A mind 400 years ahead of its time, building wonders in a hidden workshop", color: "#FFD700", iconColor: "#1A1A1A", categorySlug: "visionaries-inventors", characterName: "Leonardo da Vinci", storyAngle: "The flying machine obsession" },
  { icon: "skull", title: "Medusa: The Cursed Beauty", desc: "Not a monster — a victim of the gods, cursed for being too beautiful", color: "#4B0082", iconColor: "#00FF88", categorySlug: "dark-legends", characterName: "Medusa", storyAngle: "Retelling where the monster is the tragic hero" },
  { icon: "skull", title: "Rasputin: The Man Who Would Not Die", desc: "Poisoned, shot, beaten, drowned — and still he whispered", color: "#4B0082", iconColor: "#00FF88", categorySlug: "dark-legends", characterName: "Rasputin", storyAngle: "The night they tried to kill the unkillable" },
  { icon: "bolt", title: "The Fallen Star: Exile from the Sky", desc: "An alien exile with solar powers, torn between two worlds that reject him", color: "#0066FF", iconColor: "#FFF", categorySlug: "fallen-heroes", characterName: "The Fallen Star", storyAngle: "Protect a world that fears you, or return to one that rejected you" },
  { icon: "bolt", title: "The Dark Sentinel: Shadows of Justice", desc: "A vigilante who fights crime but questions if fear makes the city safer", color: "#0066FF", iconColor: "#FFF", categorySlug: "fallen-heroes", characterName: "The Dark Sentinel", storyAngle: "The cost of becoming what you fight" },
  { icon: "diamond", title: "Cleopatra: The Last Pharaoh", desc: "She seduced empires and chose death over submission to Rome", color: "#DC143C", iconColor: "#FFD700", categorySlug: "queens-seducers", characterName: "Cleopatra", storyAngle: "Political genius disguised as seduction" },
  { icon: "diamond", title: "Wu Zetian: The Dragon Empress", desc: "From concubine to the only woman to rule China as emperor", color: "#DC143C", iconColor: "#FFD700", categorySlug: "queens-seducers", characterName: "Wu Zetian", storyAngle: "Ruthless intelligence behind the silk curtain" },
  { icon: "whatshot", title: "The Last Day of Pompeii", desc: "Multiple lives caught in Vesuvius' eruption — a merchant, a slave, a priest", color: "#FF6600", iconColor: "#FFF", categorySlug: "doomsday-prophecy", storyAngle: "The sky turns to fire in 79 AD" },
  { icon: "whatshot", title: "Ragnarok: The Twilight of Gods", desc: "The final battle where gods die and the world burns so something new can begin", color: "#FF6600", iconColor: "#FFF", categorySlug: "doomsday-prophecy", storyAngle: "Norse end-of-days — death and rebirth" },
  { icon: "shield", title: "Caesar's Blood: The Ides of March", desc: "The assassination told in reverse — starting with betrayal, ending with rise", color: "#8B0000", iconColor: "#FFD700", categorySlug: "conquerors-kings", characterName: "Julius Caesar", storyAngle: "Et tu, Brute?" },
  { icon: "skull", title: "Vlad the Impaler: Lord of Darkness", desc: "The real Dracula — tactics so brutal they became immortal legend", color: "#4B0082", iconColor: "#00FF88", categorySlug: "dark-legends", characterName: "Vlad III", storyAngle: "Defending Wallachia through terror" },
];
